# Generated by Django 2.1.7 on 2019-02-24 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_key', models.IntegerField()),
                ('company', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_Done', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('session', models.CharField(max_length=300)),
                ('Businesskey', models.ManyToManyField(related_name='key', to='newapp.Group')),
            ],
        ),
    ]
